name = "SGtSNEpi"
uuid = "e6c19c8d-e382-4a50-b2c6-174ddd647730"
authors = ["Nikos Pitsianis <nikos@cs.duke.edu>", "Dimitris Floros <fcdimitr@ece.auth.gr>", "Alexandros-Stavros Iliopoulos <ailiop@mit.edu>", "Xiaobai Sun <xiaobai@cs.duke.edu>"]
version = "0.3.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FLANN = "4ef67f76-e0de-5105-ac01-03b6482fb4f8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
sgtsnepi_jll = "c2c51ba6-9464-585c-93d5-ba434ab08fad"

[compat]
Colors = "0.12"
Distances = "0.10"
Graphs = "1"
FLANN = "1"
Hwloc = "2"
NearestNeighbors = "0.4"
Requires = "1"
julia = "1.6"
sgtsnepi_jll = "2"

[extras]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Makie"]
