[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterLaTeX = "cd674d7a-5f81-5cf3-af33-235ef1834b99"
ImageFeatures = "92ff4b2b-8094-53d3-b29d-97f740f06cef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SGtSNEpi = "e6c19c8d-e382-4a50-b2c6-174ddd647730"
